/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horizon.airways;

import java.awt.print.PrinterException;
import java.sql.*; 
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*; 

/**
 *
 * @author Ibro
 */
public class HorizonAirwaysGUI extends javax.swing.JFrame {

    /**
     * Creates new form HorizonAirwaysGUI
     */
     
    Connection con;
    ResultSet rs;
    Statement st;
    PreparedStatement pst;
    String tradn, tradnew, randb, fnam, lnam, statu, amo;
    
    
    public HorizonAirwaysGUI() {
        initComponents();
        this.setLocationRelativeTo(null); // to make the program appear at the center 
        this.setResizable(false); // to make the program not resizable
        rb1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maintab = new javax.swing.JPanel();
        logintab = new javax.swing.JPanel();
        cass_tab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JTextField();
        loginrtxt = new javax.swing.JButton();
        loginctxt = new javax.swing.JButton();
        bmtxt = new javax.swing.JButton();
        busmg_tab = new javax.swing.JPanel();
        gbbox = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userbox = new javax.swing.JTextField();
        passbox = new javax.swing.JTextField();
        loginbox = new javax.swing.JButton();
        reservationtab = new javax.swing.JPanel();
        resone = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        selback = new javax.swing.JButton();
        selsector = new javax.swing.JComboBox();
        seltrad = new javax.swing.JComboBox();
        selclass = new javax.swing.JComboBox();
        selsub = new javax.swing.JButton();
        selcan = new javax.swing.JButton();
        infotwo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox();
        seatpref = new javax.swing.JComboBox();
        seatzone = new javax.swing.JComboBox();
        mealpref = new javax.swing.JComboBox();
        ssr = new javax.swing.JComboBox();
        status = new javax.swing.JComboBox();
        subinfo = new javax.swing.JButton();
        caninfo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnrtab = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnrfield = new javax.swing.JTextField();
        amofield = new javax.swing.JLabel();
        colamo = new javax.swing.JButton();
        pnrrec = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        priamo = new javax.swing.JButton();
        rb1 = new javax.swing.JButton();
        cancellationtab = new javax.swing.JPanel();
        canone = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        canback = new javax.swing.JButton();
        pnrveri = new javax.swing.JTextField();
        canveri = new javax.swing.JButton();
        veribox = new javax.swing.JLabel();
        bday = new javax.swing.JButton();
        lday = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bcantwo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bramo = new javax.swing.JLabel();
        brbut = new javax.swing.JButton();
        brrec = new javax.swing.JButton();
        brtab = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        lcantwo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lramo = new javax.swing.JLabel();
        lrbut = new javax.swing.JButton();
        lrrec = new javax.swing.JButton();
        lrtab = new javax.swing.JScrollPane();
        area3 = new javax.swing.JTextArea();
        repprotab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rptab = new javax.swing.JTabbedPane();
        reptab = new javax.swing.JPanel();
        reprec = new javax.swing.JScrollPane();
        area55 = new javax.swing.JTextArea();
        protab = new javax.swing.JPanel();
        prorec = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maintab.setLayout(new java.awt.CardLayout());

        logintab.setLayout(new java.awt.CardLayout());

        cass_tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Counter Assistant");
        cass_tab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 270, 30));

        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        cass_tab.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 350, 70));
        cass_tab.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 350, 70));

        loginrtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginrtxt.setText("Login for Reservation");
        loginrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginrtxtActionPerformed(evt);
            }
        });
        cass_tab.add(loginrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 150, 50));

        loginctxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginctxt.setText("Login for Cancellation");
        loginctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginctxtActionPerformed(evt);
            }
        });
        cass_tab.add(loginctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 150, 50));

        bmtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bmtxt.setText("Login as Business Manager");
        bmtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmtxtActionPerformed(evt);
            }
        });
        cass_tab.add(bmtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 210, 50));

        logintab.add(cass_tab, "card2");

        busmg_tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gbbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gbbox.setText("Go Back");
        gbbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbboxActionPerformed(evt);
            }
        });
        busmg_tab.add(gbbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("Welcome Business Manager");
        busmg_tab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 270, 30));

        userbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userboxActionPerformed(evt);
            }
        });
        busmg_tab.add(userbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 350, 70));
        busmg_tab.add(passbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 350, 70));

        loginbox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        loginbox.setText("Login");
        loginbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginboxActionPerformed(evt);
            }
        });
        busmg_tab.add(loginbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 150, 50));

        logintab.add(busmg_tab, "card3");

        maintab.add(logintab, "card2");

        reservationtab.setLayout(new java.awt.CardLayout());

        resone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Make a Reservation");
        resone.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 280, 40));

        selback.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selback.setText("Go Back");
        selback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selbackActionPerformed(evt);
            }
        });
        resone.add(selback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        selsector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selsector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Sector", "Chicago to New-York", "Memphis to New-York", "Miami to New-York", "New-Orleans to New-York", "New-York to Chicago", "New-York to Memphis", "New-York to Miami", "New-York to New-Orleans", "New-York to Pittsburgh", "Pittsburgh to New-York", "" }));
        selsector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selsectorActionPerformed(evt);
            }
        });
        resone.add(selsector, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 250, 40));

        seltrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seltrad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Travel Date" }));
        seltrad.setEnabled(false);
        seltrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seltradActionPerformed(evt);
            }
        });
        resone.add(seltrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 230, 40));

        selclass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Class" }));
        selclass.setEnabled(false);
        resone.add(selclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 250, 40));

        selsub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selsub.setText("Submit");
        selsub.setToolTipText("");
        selsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selsubActionPerformed(evt);
            }
        });
        resone.add(selsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 150, 40));

        selcan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selcan.setText("Cancel");
        selcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selcanActionPerformed(evt);
            }
        });
        resone.add(selcan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 150, 40));

        reservationtab.add(resone, "card2");

        infotwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Customer Details");
        infotwo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 200, 30));
        infotwo.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 40));
        infotwo.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 200, 40));
        infotwo.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 70, 40));

        gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gender", "M", "F" }));
        infotwo.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 200, 40));

        seatpref.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        seatpref.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seat Pref", "Aisle", "Window" }));
        infotwo.add(seatpref, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 200, 40));

        seatzone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        seatzone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seat Zone", "Smoking", "Non-Smoking" }));
        infotwo.add(seatzone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, 40));

        mealpref.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mealpref.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meal Pref", "Vegeterian", "Non-Vegeterian" }));
        infotwo.add(mealpref, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 200, 40));

        ssr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ssr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SSR", "Heart", "Body", "Other" }));
        infotwo.add(ssr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 200, 40));

        status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Status", "Confirmed", "Over-Booked", "Wait-Listed" }));
        infotwo.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 200, 40));

        subinfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subinfo.setText("Submit");
        subinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subinfoActionPerformed(evt);
            }
        });
        infotwo.add(subinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 160, 40));

        caninfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        caninfo.setText("Cancel");
        caninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caninfoActionPerformed(evt);
            }
        });
        infotwo.add(caninfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 160, 40));

        jLabel9.setText("Firstname:");
        infotwo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel10.setText("Age:");
        infotwo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel12.setText("Lastname:");
        infotwo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        reservationtab.add(infotwo, "card3");

        pnrtab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Customer PNR");
        pnrtab.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 40));

        pnrfield.setEditable(false);
        pnrfield.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        pnrfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnrfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnrfieldActionPerformed(evt);
            }
        });
        pnrtab.add(pnrfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 390, 40));

        amofield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amofield.setText("0.00");
        amofield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnrtab.add(amofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 300, 41));

        colamo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        colamo.setText("Collected");
        colamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colamoActionPerformed(evt);
            }
        });
        pnrtab.add(colamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 120, 40));

        area1.setEditable(false);
        area1.setColumns(20);
        area1.setRows(5);
        pnrrec.setViewportView(area1);

        pnrtab.add(pnrrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 700, 240));

        priamo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priamo.setText("Print");
        priamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priamoActionPerformed(evt);
            }
        });
        pnrtab.add(priamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 120, 30));

        rb1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rb1.setText("Go Back");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        pnrtab.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        reservationtab.add(pnrtab, "card4");

        maintab.add(reservationtab, "card3");

        cancellationtab.setLayout(new java.awt.CardLayout());

        canone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cancel a Reservation");
        canone.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 280, 40));

        canback.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        canback.setText("Go Back");
        canback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbackActionPerformed(evt);
            }
        });
        canone.add(canback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));
        canone.add(pnrveri, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 380, 50));

        canveri.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        canveri.setText("Verify");
        canveri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canveriActionPerformed(evt);
            }
        });
        canone.add(canveri, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 110, 50));

        veribox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        veribox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        veribox.setText("Undefined");
        canone.add(veribox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 300, 30));

        bday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bday.setText("Before a Day");
        bday.setEnabled(false);
        bday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdayActionPerformed(evt);
            }
        });
        canone.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 150, 50));

        lday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lday.setText("Less than a Day");
        lday.setEnabled(false);
        lday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldayActionPerformed(evt);
            }
        });
        canone.add(lday, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 150, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        canone.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 130, 40));

        cancellationtab.add(canone, "card2");

        bcantwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Refund Tab");
        bcantwo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 250, 30));

        bramo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        bramo.setText("0.00");
        bramo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bcantwo.add(bramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 350, 63));

        brbut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        brbut.setText("Refund");
        brbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brbutActionPerformed(evt);
            }
        });
        bcantwo.add(brbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 100, 50));

        brrec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        brrec.setText("Print Receipt");
        brrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brrecActionPerformed(evt);
            }
        });
        bcantwo.add(brrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 170, 40));

        area2.setColumns(20);
        area2.setRows(5);
        brtab.setViewportView(area2);

        bcantwo.add(brtab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 700, 280));

        cancellationtab.add(bcantwo, "card3");

        lcantwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Refund Tab");
        lcantwo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 250, 30));

        lramo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        lramo.setText("0.00");
        lramo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lcantwo.add(lramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 350, 63));

        lrbut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lrbut.setText("Refund");
        lrbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrbutActionPerformed(evt);
            }
        });
        lcantwo.add(lrbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 100, 50));

        lrrec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lrrec.setText("Print Receipt");
        lrrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrrecActionPerformed(evt);
            }
        });
        lcantwo.add(lrrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 170, 40));

        area3.setColumns(20);
        area3.setRows(5);
        lrtab.setViewportView(area3);

        lcantwo.add(lrtab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 700, 280));

        cancellationtab.add(lcantwo, "card3");

        maintab.add(cancellationtab, "card4");

        repprotab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reports and Processing Tab");
        repprotab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 28, 387, 70));

        area55.setColumns(20);
        area55.setRows(5);
        reprec.setViewportView(area55);

        javax.swing.GroupLayout reptabLayout = new javax.swing.GroupLayout(reptab);
        reptab.setLayout(reptabLayout);
        reptabLayout.setHorizontalGroup(
            reptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reprec, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        reptabLayout.setVerticalGroup(
            reptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reprec, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        rptab.addTab("Flights Tab", reptab);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        prorec.setViewportView(jTextArea3);

        javax.swing.GroupLayout protabLayout = new javax.swing.GroupLayout(protab);
        protab.setLayout(protabLayout);
        protabLayout.setHorizontalGroup(
            protabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prorec, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        protabLayout.setVerticalGroup(
            protabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prorec, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        rptab.addTab("Passenger Tab", protab);

        repprotab.add(rptab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, -1, -1));

        maintab.add(repprotab, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maintab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maintab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void userboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userboxActionPerformed

    private void bmtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmtxtActionPerformed
        maintab.removeAll();
        maintab.validate();
        maintab.repaint();
        maintab.add(busmg_tab);
        maintab.repaint();
        maintab.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_bmtxtActionPerformed

    private void gbboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbboxActionPerformed
        maintab.removeAll();
        maintab.validate();
        maintab.repaint();
        maintab.add(cass_tab);
        maintab.repaint();
        maintab.revalidate(); // TODO add your handling code here:
    }//GEN-LAST:event_gbboxActionPerformed

    private void loginrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginrtxtActionPerformed
    try{
        con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
        String sql = "select * from Users where UserName=? and Password=?";
        pst = con.prepareStatement(sql);
        pst.setString(1, usertxt.getText());
        pst.setString(2, passtxt.getText());
        rs = pst.executeQuery();
        
        if(rs.next()){
            JOptionPane.showMessageDialog(null, "Username and Password Matched");
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(reservationtab);
            maintab.repaint();
            maintab.revalidate();
        }else{
            JOptionPane.showMessageDialog(null, "Username and Password not Correct");
            usertxt.setText("");
            passtxt.setText("");
        }
        con.close();
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginrtxtActionPerformed

    private void loginboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginboxActionPerformed
    try{
        con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
        String sql = "select * from Users where UserName=? and Password=?";
        pst = con.prepareStatement(sql);
        pst.setString(1, userbox.getText());
        pst.setString(2, passbox.getText());
        rs = pst.executeQuery();
       
        if(rs.next()){
            JOptionPane.showMessageDialog(null, "Username and Password Matched");
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(repprotab);
            maintab.repaint();
            maintab.revalidate();
        }else{
            JOptionPane.showMessageDialog(null, "Username and Password not Correct");
            usertxt.setText("");
            passtxt.setText("");
        }
        con.close();
        
        con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
        String sqll = "select * from passenger;";
        st = con.createStatement();
        rs = st.executeQuery(sqll);
        
        String Userdata = "";
        
        while(rs.next()){
            Userdata = rs.getString(1) + " " + rs.getString(4) + " " + rs.getString(5) + " " + rs.getString(6) + " " + rs.getString(7) + " " + rs.getString(8) + " " + rs.getString(9) + " " + rs.getString(11) + " " + rs.getString(13);
            area55.setText(Userdata);
        }
        st.close();
        con.close();
        
        
        con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
        String sqla = "select * from DailyCollection;";
        st = con.createStatement();
        rs = st.executeQuery(sqla);
        
        String Userdat = "";
        
        while(rs.next()){
            Userdat = rs.getString(1) + " " + rs.getDate(2) + " " + rs.getString(3) + " " + rs.getInt(4);
            area55.setText(Userdat);
        }
        st.close();
        con.close();
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_loginboxActionPerformed

    private void loginctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginctxtActionPerformed
try{
        con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
        String sql = "select * from Users where UserName=? and Password=?";
        pst = con.prepareStatement(sql);
        pst.setString(1, usertxt.getText());
        pst.setString(2, passtxt.getText());
        rs = pst.executeQuery();
        
        if(rs.next()){
            JOptionPane.showMessageDialog(null, "Username and Password Matched");
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(cancellationtab);
            maintab.repaint();
            maintab.revalidate();
        }else{
            JOptionPane.showMessageDialog(null, "Username and Password not Correct");
            usertxt.setText("");
            passtxt.setText("");
        }
        con.close();
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_loginctxtActionPerformed

    private void selbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selbackActionPerformed
        maintab.removeAll();
        maintab.validate();
        maintab.repaint();
        maintab.add(cass_tab);
        maintab.repaint();
        maintab.revalidate();    // TODO add your handling code here:
    }//GEN-LAST:event_selbackActionPerformed

    private void canbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canbackActionPerformed

    private void bdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdayActionPerformed
        try {
            // TODO add your handling code here:
            String pnr = pnrveri.getText();
            
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select Amount from DailyCollection where PnrNo=?;";
            pst = con.prepareStatement(sql);
            pst.setString(1, pnr);
            rs = pst.executeQuery();
            rs.next();
            String pric = rs.getString("Amount");
            pst.close();
            con.close();
            
            bramo.setText(pric);
            
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(bcantwo);
            maintab.repaint();
            maintab.revalidate();         
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bdayActionPerformed

    private void ldayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldayActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String pnr = pnrveri.getText();
            
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select Amount from DailyCollection where PnrNo=?;";
            pst = con.prepareStatement(sql);
            pst.setString(1, pnr);
            rs = pst.executeQuery();
            rs.next();
            String pric = rs.getString("Amount");
            pst.close();
            con.close();
            
            double qwe, qwer, qwert;
                    qwe = Double.parseDouble(pric);
                    qwer = qwe/10;
                    qwert = qwe - qwer;
            String pricc = Double.toString(qwert);
            lramo.setText(pricc);
            
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(lcantwo);
            maintab.repaint();
            maintab.revalidate();         
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ldayActionPerformed

    private void brbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brbutActionPerformed
        // TODO add your handling code here:
            String pnr = pnrveri.getText();   
            
            area2.setText("******************************************************************************************************************************************" + "\n");
            area2.setText(area2.getText() + "                                                                       Horizon Airways" + "\n");
            area2.setText(area2.getText() + "                                                                       Passenger Details" + "\n");
            area2.setText(area2.getText() + "******************************************************************************************************************************************" + "\n\n");
            area2.setText(area2.getText() + "PNR Number: " + pnr  + "\n\n");
            area2.setText(area2.getText() + "Refunded Amount: " + bramo.getText()  + "\n\n");
            area2.setText(area2.getText() + "                                                                                                                                                       Signature: " );
    }//GEN-LAST:event_brbutActionPerformed

    private void lrbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrbutActionPerformed
        // TODO add your handling code here:
        String pnr = pnrveri.getText();   
            
            area3.setText("******************************************************************************************************************************************" + "\n");
            area3.setText(area3.getText() + "                                                                       Horizon Airways" + "\n");
            area3.setText(area3.getText() + "                                                                       Passenger Details" + "\n");
            area3.setText(area3.getText() + "******************************************************************************************************************************************" + "\n\n");
            area3.setText(area3.getText() + "PNR Number: " + pnr  + "\n\n");
            area3.setText(area3.getText() + "Refunded Amount: " + lramo.getText()  + "\n\n");
            area3.setText(area3.getText() + "                                                                                                                                                       Signature: " );
    }//GEN-LAST:event_lrbutActionPerformed

    private void selsectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selsectorActionPerformed
        if(selsector.getSelectedItem().equals("Chicago to New-York")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-04");
            seltrad.addItem("2020-03-07");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else if(selsector.getSelectedItem().equals("Memphis to New-York")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-03");
            seltrad.addItem("2020-03-06");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else if(selsector.getSelectedItem().equals("Miami to New-York")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-03");
            seltrad.addItem("2020-03-13");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else if(selsector.getSelectedItem().equals("New-Orleans to New-York")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-02");
            seltrad.addItem("2020-03-05");   
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else if (selsector.getSelectedItem().equals("New-York to Chicago")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-11");
            seltrad.addItem("2020-03-14");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else if(selsector.getSelectedItem().equals("New-York to Memphis")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-01");
            seltrad.addItem("2020-03-10"); 
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if(selsector.getSelectedItem().equals("New-York to Miami")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-10");
            seltrad.addItem("2020-03-13");  
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else if(selsector.getSelectedItem().equals("New-York to New-Orleans") ){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-02");
            seltrad.addItem("2020-03-05"); 
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else if (selsector.getSelectedItem().equals("New-York to Pittsburgh")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-09");
            seltrad.addItem("2020-03-12"); 
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else if(selsector.getSelectedItem().equals("Pittsburgh to New-York")){
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-09");
            seltrad.addItem("2020-03-12"); 
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Choose a Valid Sector :(");
        }
    }//GEN-LAST:event_selsectorActionPerformed

    private void seltradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seltradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seltradActionPerformed

    private void selsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selsubActionPerformed
        try {
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select FlightNo from Flights where FlightDate = ?;";
            pst = con.prepareStatement(sql);
            String trad = seltrad.getSelectedItem().toString();
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date = sdf1.parse(trad);
            java.sql.Date sqltrad = new java.sql.Date(date.getTime());
            tradnew = sqltrad.toString();
            pst.setString(1, tradnew);
            rs = pst.executeQuery();
            rs.next();
            tradn = rs.getString("FlightNo");
            pst.close();
            con.close();
            System.out.println(tradnew);
            System.out.println(tradn);
            
            
            if(selclass.getSelectedItem().equals("First Class")){
                con = HorizonAirways.getConnection();
                String sqll = "select FirstClassSeatsAvailable from ScheduledFlights where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqll);
                pst.setString(1, tradn);
                pst.setString(2, tradnew);
                rs = pst.executeQuery();
                rs.next();
                String cls = rs.getString("FirstClassSeatsAvailable");
                
                int clsa = Integer.parseInt(cls);
                int clsb = clsa - 1;
            
                
                pst.close();
                con.close();
                
                System.out.println(cls);
                System.out.println(clsa);
                System.out.println(clsb);
                
                con = HorizonAirways.getConnection();
                String sqlll = "update ScheduledFlights set FirstClassSeatsAvailable=? where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqlll);
                pst.setInt(1, clsb);
                pst.setString(2, tradn);
                pst.setString(3, tradnew);
                pst.executeUpdate(); //this
                JOptionPane.showMessageDialog(this, "Update Sucessful :)");
               
                pst.close();
                con.close();
                
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(infotwo);
            maintab.repaint();
            maintab.revalidate();
            }else if(selclass.getSelectedItem().equals("Business Class")){
                con = HorizonAirways.getConnection();
                String sqll = "select BusinessClassSeatsAvailable from ScheduledFlights where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqll);
                pst.setString(1, tradn);
                pst.setString(2, tradnew);
                rs = pst.executeQuery();
                rs.next();
                String cls = rs.getString("BusinessClassSeatsAvailable");
                
                int clsa = Integer.parseInt(cls);
                int clsb = clsa - 1;
            
                
                pst.close();
                con.close();
                
                System.out.println(cls);
                System.out.println(clsa);
                System.out.println(clsb);
                
                con = HorizonAirways.getConnection();
                String sqlll = "update ScheduledFlights set BusinessClassSeatsAvailable=? where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqlll);
                pst.setInt(1, clsb);
                pst.setString(2, tradn);
                pst.setString(3, tradnew);
                pst.executeUpdate(); //this
                JOptionPane.showMessageDialog(this, "Update Sucessful :)");
               
                pst.close();
                con.close();
                
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(infotwo);
            maintab.repaint();
            maintab.revalidate();
            }else if(selclass.getSelectedItem().equals("Economy Class")){
                con = HorizonAirways.getConnection();
                String sqll = "select EconomyClassSeatsAvailable from ScheduledFlights where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqll);
                pst.setString(1, tradn);
                pst.setString(2, tradnew);
                rs = pst.executeQuery();
                rs.next();
                String cls = rs.getString("EconomyClassSeatsAvailable");
                
                int clsa = Integer.parseInt(cls);
                int clsb = clsa - 1;
            
                
                pst.close();
                con.close();
                
                System.out.println(cls);
                System.out.println(clsa);
                System.out.println(clsb);
                
                con = HorizonAirways.getConnection();
                String sqlll = "update ScheduledFlights set EconomyClassSeatsAvailable=? where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqlll);
                pst.setInt(1, clsb);
                pst.setString(2, tradn);
                pst.setString(3, tradnew);
                pst.executeUpdate(); //this
                JOptionPane.showMessageDialog(this, "Update Sucessful :)");
               
                pst.close();
                con.close();
                
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(infotwo);
            maintab.repaint();
            maintab.revalidate();
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Details Selected :(");
            }
            pst.close();
            con.close();
            
            
            
        } catch (ClassNotFoundException | ParseException | SQLException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_selsubActionPerformed

    private void selcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selcanActionPerformed
    seltrad.removeAllItems();
    seltrad.addItem("Choose a Travel Date");
    seltrad.setEnabled(false);
    selclass.removeAllItems();
    selclass.addItem("Choose a Class");
    selclass.setEnabled(false);
    }//GEN-LAST:event_selcanActionPerformed

    private void subinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subinfoActionPerformed
        try {
            con = HorizonAirways.getConnection();
            
                Random rand = new Random();
                    int randa = rand.nextInt(100000000);
                    randb = Integer.toString(randa);
                String travno = tradn;
                String travda = tradnew;
                fnam = fname.getText();
                lnam = lname.getText();
                String agea = age.getText();
                    int ageb = Integer.parseInt(agea);
                String gende = gender.getSelectedItem().toString();
                String clas = selclass.getSelectedItem().toString();
                String seatpre = seatpref.getSelectedItem().toString();
                String seatzon = seatzone.getSelectedItem().toString();
                String mealpre = mealpref.getSelectedItem().toString();
                String ssra = ssr.getSelectedItem().toString();
                statu = status.getSelectedItem().toString();
                
                System.out.println(randb);
                System.out.println(travno);
                System.out.println(travda);
                System.out.println(fnam);
                System.out.println(lnam);
                System.out.println(ageb);
                System.out.println(gende);
                System.out.println(clas);
                System.out.println(seatpre);
                System.out.println(seatzon);
                System.out.println(mealpre);
                System.out.println(ssra);
                System.out.println(statu);
                
                String sqlaba = "insert into Passenger values(?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
                                       
                pst = con.prepareStatement(sqlaba);
                pst.setString(1, randb);
                pst.setString(2, travno);
                pst.setString(3, travda);
                pst.setString(4, fnam);
                pst.setString(5, lnam);
                pst.setInt(6, ageb);
                pst.setString(7, gende);
                pst.setString(8, clas);
                pst.setString(9, seatpre);
                pst.setString(10, seatzon);
                pst.setString(11, mealpre);
                pst.setString(12, ssra);
                pst.setString(13, statu);
                pst.setString(14, "N");
          
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Passenger Details has been Uploaded :)");
                
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(pnrtab);
            maintab.repaint();
            maintab.revalidate();
            
            pnrfield.setText(randb);
            
            price();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_subinfoActionPerformed

    private void pnrfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnrfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnrfieldActionPerformed

    private void colamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colamoActionPerformed
        try {
            // TODO add your handling code here:
            
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sqlllll = "select DepTime from Flights where FlightNo=? and FlightDate=?;";
            pst = con.prepareStatement(sqlllll);
            pst.setString(1, tradn);
            pst.setString(2, tradnew);
            rs = pst.executeQuery();
            rs.next();
            String dept = rs.getString("DepTime");
            pst.close();
            con.close();
            
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sqllll = "select ArrTime from Flights where FlightNo=? and FlightDate=?;";
            pst = con.prepareStatement(sqllll);
            pst.setString(1, tradn);
            pst.setString(2, tradnew);
            rs = pst.executeQuery();
            rs.next();
            String arrt = rs.getString("ArrTime");
            pst.close();
            con.close();
            
            con = HorizonAirways.getConnection(); // this
            String sqrl = "insert into DailyCollection values (?,?,?,?);";
            pst = con.prepareStatement(sqrl);
            pst.setString(1, randb);
            pst.setString(2, java.time.LocalDateTime.now().toString()); //this
            pst.setString(3, "C");
            Double amoo = Double.parseDouble(amo); 
                pst.setDouble(4, amoo);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Daily Collection File Updated :)");
            pst.close();
            con.close();
            
            area1.setText("******************************************************************************************************************************************" + "\n");
            area1.setText(area1.getText() + "                                                                       Horizon Airways" + "\n");
            area1.setText(area1.getText() + "                                                                       Passenger Details" + "\n");
            area1.setText(area1.getText() + "******************************************************************************************************************************************" + "\n\n");
            area1.setText(area1.getText() + "                                                                                                                                                       Date of issue: " + java.time.LocalDate.now() + "\n\n\n\n");
            area1.setText(area1.getText() + "NOT TRANSFERABLE" + "\n\n");
            area1.setText(area1.getText() + "Passenger Name: " + fnam + "   " + lnam + "\n\n");
            area1.setText(area1.getText() + "Sector: " + (String) selsector.getSelectedItem() + "\n\n");
            area1.setText(area1.getText() + "Flight: " + tradn + "      Class: " + (String) selclass.getSelectedItem() + "      Date: " + tradnew + "       Dep. Time: " + dept + "     Arr. Time: " + arrt + "     Status: " + statu + "\n\n");
            area1.setText(area1.getText() + "                                                                                                                                                       Signature: ");
        
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        rb1.setVisible(true);
    }//GEN-LAST:event_colamoActionPerformed

    private void priamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priamoActionPerformed
        try {
            // TODO add your handling code here:

            area1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_priamoActionPerformed

    private void caninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caninfoActionPerformed
    fname.setText("");
    lname.setText("");
    age.setText("");
    gender.setSelectedItem("Gender");
    mealpref.setSelectedItem("Meal Pref");
    seatzone.setSelectedItem("Seat Zone");
    seatpref.setSelectedItem("Seat Pref");
    ssr.setSelectedItem("SSR");
    status.setSelectedItem("Status");
// TODO add your handling code here:
    }//GEN-LAST:event_caninfoActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(resone);
            maintab.repaint();
            maintab.revalidate();
    }//GEN-LAST:event_rb1ActionPerformed

    private void canveriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canveriActionPerformed
        // TODO add your handling code here:
        String pnr = pnrveri.getText();
        
        try{
        con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
        String sql = "select PnrNo from Passenger where PnrNo=?";
        pst = con.prepareStatement(sql);
        pst.setString(1, pnr);
        rs = pst.executeQuery();
       
        if(rs.next()){
            veribox.setText("Verified :)");
            bday.setEnabled(true);
            lday.setEnabled(true);
        }else{
            veribox.setText("Not Verified :(");
        }
        pst.close();
        con.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_canveriActionPerformed

    private void lrrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrrecActionPerformed
        try {
            // TODO add your handling code here:
            area3.print();
        } catch (PrinterException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lrrecActionPerformed

    private void brrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brrecActionPerformed
        try {
            // TODO add your handling code here:
            area2.print();
        } catch (PrinterException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brrecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HorizonAirwaysGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JLabel amofield;
    private javax.swing.JTextArea area1;
    private javax.swing.JTextArea area2;
    private javax.swing.JTextArea area3;
    private javax.swing.JTextArea area55;
    private javax.swing.JPanel bcantwo;
    private javax.swing.JButton bday;
    private javax.swing.JButton bmtxt;
    private javax.swing.JLabel bramo;
    private javax.swing.JButton brbut;
    private javax.swing.JButton brrec;
    private javax.swing.JScrollPane brtab;
    private javax.swing.JPanel busmg_tab;
    private javax.swing.JButton canback;
    private javax.swing.JPanel cancellationtab;
    private javax.swing.JButton caninfo;
    private javax.swing.JPanel canone;
    private javax.swing.JButton canveri;
    private javax.swing.JPanel cass_tab;
    private javax.swing.JButton colamo;
    private javax.swing.JTextField fname;
    private javax.swing.JButton gbbox;
    private javax.swing.JComboBox gender;
    private javax.swing.JPanel infotwo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel lcantwo;
    private javax.swing.JButton lday;
    private javax.swing.JTextField lname;
    private javax.swing.JButton loginbox;
    private javax.swing.JButton loginctxt;
    private javax.swing.JButton loginrtxt;
    private javax.swing.JPanel logintab;
    private javax.swing.JLabel lramo;
    private javax.swing.JButton lrbut;
    private javax.swing.JButton lrrec;
    private javax.swing.JScrollPane lrtab;
    private javax.swing.JPanel maintab;
    private javax.swing.JComboBox mealpref;
    private javax.swing.JTextField passbox;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField pnrfield;
    private javax.swing.JScrollPane pnrrec;
    private javax.swing.JPanel pnrtab;
    private javax.swing.JTextField pnrveri;
    private javax.swing.JButton priamo;
    private javax.swing.JScrollPane prorec;
    private javax.swing.JPanel protab;
    private javax.swing.JButton rb1;
    private javax.swing.JPanel repprotab;
    private javax.swing.JScrollPane reprec;
    private javax.swing.JPanel reptab;
    private javax.swing.JPanel reservationtab;
    private javax.swing.JPanel resone;
    private javax.swing.JTabbedPane rptab;
    private javax.swing.JComboBox seatpref;
    private javax.swing.JComboBox seatzone;
    private javax.swing.JButton selback;
    private javax.swing.JButton selcan;
    private javax.swing.JComboBox selclass;
    private javax.swing.JComboBox selsector;
    private javax.swing.JButton selsub;
    private javax.swing.JComboBox seltrad;
    private javax.swing.JComboBox ssr;
    private javax.swing.JComboBox status;
    private javax.swing.JButton subinfo;
    private javax.swing.JTextField userbox;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel veribox;
    // End of variables declaration//GEN-END:variables

    private void price() {
        if(selsector.getSelectedItem().equals("Chicago to New-York") && selclass.getSelectedItem().equals("First Class")){
            amo = "400.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("Chicago to New-York") && selclass.getSelectedItem().equals("Business Class")){
            amo = "330.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("Chicago to New-York") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "250.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("Memphis to New-York") && selclass.getSelectedItem().equals("First Class")){
            amo = "430.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("Memphis to New-York") && selclass.getSelectedItem().equals("Business Class")){
            amo = "330.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("Memphis to New-York") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "240.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("Miami to New-York") && selclass.getSelectedItem().equals("First Class")){
            amo = "410.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("Miami to New-York") && selclass.getSelectedItem().equals("Business Class")){
            amo = "310.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("Miami to New-York") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "260.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("New-Orleans to New-York") && selclass.getSelectedItem().equals("First Class")){
            amo = "450.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-Orleans to New-York") && selclass.getSelectedItem().equals("Business Class")){
            amo = "380.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-Orleans to New-York") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "330.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("New-York to Chicago") && selclass.getSelectedItem().equals("First Class")){
            amo = "400.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to Chicago") && selclass.getSelectedItem().equals("Business Class")){
            amo = "330.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to Chicago") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "250.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("New-York to Memphis") && selclass.getSelectedItem().equals("First Class")){
            amo = "430.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to Memphis") && selclass.getSelectedItem().equals("Business Class")){
            amo = "330.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to Memphis") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "240.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("New-York to Miami") && selclass.getSelectedItem().equals("First Class")){
            amo = "380.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to Miami") && selclass.getSelectedItem().equals("Business Class")){
            amo = "310.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to Miami") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "260.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("New-York to New-Orleans") && selclass.getSelectedItem().equals("First Class")){
            amo = "450.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to New-Orleans") && selclass.getSelectedItem().equals("Business Class")){
            amo = "380.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to New-Orleans") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "330.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("New-York to Pittsburgh") && selclass.getSelectedItem().equals("First Class")){
            amo = "200.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to Pittsburgh") && selclass.getSelectedItem().equals("Business Class")){
            amo = "150.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("New-York to Pittsburgh") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "120.00";
            amofield.setText(amo);
        }else   if(selsector.getSelectedItem().equals("Pittsburgh to New-York") && selclass.getSelectedItem().equals("First Class")){
            amo = "200.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("Pittsburgh to New-York") && selclass.getSelectedItem().equals("Business Class")){
            amo = "150.00";
            amofield.setText(amo);
        }else if(selsector.getSelectedItem().equals("Pittsburgh to New-York") && selclass.getSelectedItem().equals("Economy Class")){
            amo = "100.00";
            amofield.setText(amo);
        }else{
            amo = "Error getting Price!";
            JOptionPane.showMessageDialog(this, amo);
            amofield.setText(amo);
        }
    }

}
